mysql:
  image:
    registry: 192.168.0.103:5000
    repository: bitnami/mysql
    tag: 8.4.3-debian-12-r0

  auth:
    rootPassword: root123456
    database: fota_web_platform


redis:
  architecture: standalone

  image:
    registry: 192.168.0.103:5000
    repository: bitnami/redis
    tag: latest

  auth:
    enabled: false


minio:
  image:
    registry: 192.168.0.103:5000
    repository: bitnamilegacy/minio
    tag: 2025.7.23-debian-12-r5

  auth:
    rootUser: minioadmin
    rootPassword: minioadmin123

  defaultBuckets: "fota-firmware,device-firmware"
