server {
    listen 80;
    server_name yefeng001.xyz admin.yefeng001.xyz;

    # 强制跳 HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name yefeng001.xyz admin.yefeng001.xyz;

    ssl_certificate /etc/nginx/ssl/yefeng001.xyz_bundle.pem;
    ssl_certificate_key /etc/nginx/ssl/yefeng001.xyz.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 200m;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://fota-web-http-server:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
        proxy_pass http://fota-web-http-server:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}