brokerClusterName=FotaRocketMQCluster
brokerName=fota-broker-a
brokerId=0
brokerIP1=rocketmq-broker
listenPort=10911
namesrvAddr=rocketmq-namesrv:9876
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH