#测试 nfs 的可用性
apiVersion: v1
kind: Pod

metadata:
  name: nfs-test
  namespace: fota

spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - -c
        - "3600"

      volumeMounts:
        - name: nfs-storage
          mountPath: /data

  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: fota-nfs-pvc

#注意：volumes.name 与 volumeMounts.name 必须保持一致。
#这里的nfs-storage 只是 Pod 内部起的名字。与fota-nfs-pvc 没有任何关系。