#测试 nfs 的可用性
apiVersion: v1
kind: Pod

metadata:
  name: nfs-test
  namespace: fota

spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"

      volumeMounts:
        - name: nfs-storage
          mountPath: /data

  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: fota-nfs-pvc