server:
  port: 8081

netty:
  server:
    port: 7611

gateway:
  demo-upgrade:
    enabled: true
spring:
  application:
    name: fota-gateway
  redis:
    host: localhost
    port: 6379
    database: 0

# 对象存储服务
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: fota-fireware
#Mybatis 驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#事件推送至http-server
upgrade:
  event:
    push-url: http://localhost:8080/internal/device-upgrade/event
    update-result-url: http://localhost:8080/internal/device-upgrade/result