server:
  port: 8081

netty:
  server:
    port: 7611

gateway:
  demo-upgrade:
    enabled: true

spring:
  application:
    name: fota-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    database: 0
