apiVersion: v1
kind: Service

metadata:
  name: rocketmq-nameserver

spec:
  type: {{ .Values.nameserver.service.type }}

  selector:
    app: rocketmq-nameserver

  ports:
    - name: nameserver
      port: {{ .Values.nameserver.service.port }}
      targetPort: {{ .Values.nameserver.service.port }}
