replicaCount: 1
image:
  repository: 192.168.0.103:5000/fota-mock-device-client
  tag: fdab8e3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8082
resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: "200m"
    memory: 512Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: TZ
    value: Asia/Shanghai
  - name: JAVA_OPTS
    value: "-Xms1024m -Xmx2048m"
  - name: SERVER_PORT
    value: "8082"
  # =========================
  # Gateway
  # =========================
  - name: MOCK_DEVICE_GATEWAY_HOST
    value: fota-gateway-tcp
  - name: MOCK_DEVICE_GATEWAY_PORT
    value: "7611"
  # =========================
  # Redis
  # =========================
  - name: SPRING_REDIS_HOST
    value: fota-infra-redis-master
  - name: SPRING_REDIS_PORT
    value: "6379"
  # =========================
  # MySQL
  # 如果 mock-device 确实使用数据库
  # =========================
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://fota-infra-mysql:3306/fota_web_platform
  - name: SPRING_DATASOURCE_USERNAME
    value: root
  - name: SPRING_DATASOURCE_PASSWORD
    value: root123456
  # =========================
  # MinIO
  # 如果 mock-device 需要访问固件
  # =========================
  - name: MINIO_ENDPOINT
    value: http://fota-infra-minio:9000
  - name: MINIO_ACCESS_KEY
    value: minioadmin
  - name: MINIO_SECRET_KEY
    value: minioadmin123
  - name: MINIO_DEVICE_BUCKET_NAME
    value: device-firmware
