apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-rollout
  namespace: fota

spec:
  replicas: 3


  selector:
    matchLabels:
      app: nginx-rollout


  template:

    metadata:
      labels:
        app: nginx-rollout


    spec:

      containers:
        - name: nginx

          image: nginx:1.25-alpine

          ports:
            - containerPort: 80