server:
  port: 8082

spring:
  application:
    name: fota-mock-device-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fota_web_platform?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: yefeng
  redis:
    host: localhost
    port: 6379
    database: 1

# 设备侧的对象存储服务
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: device-fireware


netty:
  device-gateway-server:
    host: 127.0.0.1
    port: 7611


