replicaCount: 1
image:
  repository: 192.168.0.103:5000/fota-web-http-server
  tag: c58d250
  pullPolicy: IfNotPresent
serviceAccount:
  create: false
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "200m"
    memory: 256Mi
autoscaling:
  enabled: false
env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: TZ
    value: Asia/Shanghai
  - name: JAVA_OPTS
    value: "-Xms256m -Xmx512m"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://fota-infra-mysql:3306/fota_web_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
  - name: SPRING_DATASOURCE_USERNAME
    value: root
  - name: SPRING_DATASOURCE_PASSWORD
    value: root123456
  - name: SPRING_REDIS_HOST
    value: fota-infra-redis-master
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: MINIO_ENDPOINT
    value: http://fota-infra-minio:9000
  - name: MINIO_ACCESS_KEY
    value: minioadmin
  - name: MINIO_SECRET_KEY
    value: minioadmin123
  - name: MINIO_BUCKET_NAME
    value: fota-firmware
  - name: MINIO_DEVICE_BUCKET_NAME
    value: device-firmware
  - name: ROCKETMQ_NAME_SERVER
    value: rocketmq-nameserver:9876
  - name: ROCKETMQ_PRODUCER_GROUP
    value: fota-web-producer-group
  - name: ROCKETMQ_CONSUMER_GROUP
    value: fota-web-upgrade-event-consumer-group
  - name: FOTA_JWT_SECRET
    value: Replace-With-A-Long-Random-Secret-At-Least-32-Chars
  - name: GATEWAY_HTTP_URL
    value: "http://fota-gateway:8081"
  - name: MOCK_DEVICE_HTTP_URL
    value: "http://fota-mock-device:8082"
