name: FOTA CI Test

on:
  # 表示这次先不绑定 push，而是在 GitHub 的 Actions 页面手动点：Run workflow
  workflow_dispatch:

jobs:
  test-runner:
    # runs-on: self-hosted表示 GitHub Actions Job -> 寻找带 self-hosted 标签的 Runner -> yefeng-H410M-DS2V -> 家庭 Ubuntu 执行 shell
    runs-on: self-hosted
    # 而 hostname / whoami / pwd 这几个命令，是为了明确确认：这条 Job 确实是在你家 Ubuntu 上执行的，不是在 GitHub 云 Runner 上执行
    steps:
      - name: Show runner info
        run: |
          echo "===== FOTA Self-hosted Runner ====="
          echo "hostname:"
          hostname

          echo "user:"
          whoami

          echo "pwd:"
          pwd

          echo "java:"
          java -version

          echo "maven:"
          mvn -version

          echo "docker:"
          docker --version