name: FOTA CI
#验证：
#  GitHub 仓库
#  ↓
#  checkout
#  ↓
#  Runner 工作目录
#  ↓
#  fota-project 源码
#  ↓
#  Maven 多模块构建
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show runner info
        run: |
          echo "===== Runner Info ====="
          hostname
          whoami
          pwd
          java -version
          mvn -version
          docker --version

      - name: Show project files
        run: |
          ls -la

      - name: Maven build
        run: |
          mvn clean package -DskipTests